### ISSUE TITLE
some types/interface are not availaible since the 0.14

### ISSUE THREAD

**Issue by Faareoh** [the-convocation/twitter-scraper#103]
Hi,

Since 0.14, certain types that were previously exported are no longer exported. It is still possible to access `Tweet`, but impossible to import certain types such as `Mention`, `Photo`, `PlaceRaw`, `Video` ...
![image](https://github.com/user-attachments/assets/f0be7ed0-d38f-4853-a85b-a66952fda2e1)

On versions < 0.14, you could import them like this, but it's no more possible:
`import { Mention } from '@the-convocation/twitter-scraper/dist/tweets';`
![image](https://github.com/user-attachments/assets/f875e96e-938d-4e13-b6ce-0a4a819b04a6)

**Comment by karashiiro** [comment]
Should be fixed as of v0.14.1
