### ISSUE TITLE
Tweets are returned in random order

### ISSUE THREAD

**Issue by Owen3H** [the-convocation/twitter-scraper#34]
The order in which tweets are returned from `getTweets` and anything that relies on it is now seemingly random (or maybe bottom to top) in all versions, including #33 
Not sure how this happened, just Twitter things I guess 🤷🏼‍♂️ 

Maybe worth re-ordering via `timeParsed` to ensure we go from latest -> oldest. 
Although this would require grabbing all tweets, defeating the purpose of `max`.

**Comment by karashiiro** [comment]
Is it random across pages? It'll easy enough to sort each page separately, sorting all pages together will be inefficient, though.

**Comment by Owen3H** [comment]
Sorry for the late reply. I don't think there is any need for my previous suggestion anymore.
After more investigating, it seems the current situation is like so:

**Logged Out**
- Tweets are returned in order of most popular.
- Missing tweets after a cut-off point (seemingly a couple weeks ago).

**Logged In**
- All tweets returned as usual & order is still chronological.

Since there are many issues and nuances, I went ahead and [ported](https://github.com/the-convocation/twitter-scraper/compare/main...Owen3H:twitter-scraper:nitter-graphql-port) the rest of the Nitter changes which use the new GraphQL endpoints and parsing has been refactored accordingly. 

It should fix this issue entirely, but the `views` property has now gone, so a solution is required for that. https://github.com/zedeus/nitter/issues/753
There are still some things that need ironing out before I can PR, but I wanted to give you an update.
