### ISSUE TITLE
Unable to reuse cookies from json file

### ISSUE THREAD

**Issue by BodoWissemann** [the-convocation/twitter-scraper#50]
I'm saving the cookies extracted from the scraper as an Array<Cookie>.

When I try to assign the cookies to the scraper I get this error 

```
(node:78265) UnhandledPromiseRejectionWarning: Error: First argument to setCookie must be a Cookie object or string
at CookieJar.setCookie (/Users/bw/Code/Other/twittertest/node_modules/tough-cookie/lib/cookie.js:1165:13)
at /Users/bw/Code/Other/twittertest/node_modules/universalify/index.js:13:12
at new Promise (<anonymous>)
at CookieJar.setCookie (/Users/bw/Code/Other/twittertest/node_modules/universalify/index.js:7:14)
at Scraper.setCookies (/Users/bw/Code/Other/twittertest/node_modules/@the-convocation/twitter-scraper/dist/scraper.js:227:40)
```

I think this might be related to the 'loose' option in cookieJar. 

My code: 

```typescript
const cookies = await scraper.getCookies();
const serializedCookies = JSON.stringify(cookies);
writeFileSync('cookies.json', serializedCookies);
```

and 

```typescript
const loadedCookiesJSON = readFileSync('cookies.json', 'utf8');
const loadedCookies = JSON.parse(loadedCookiesJSON) as Array<Cookie>; // type from 'tough-cookie'
await scraper.setCookies(loadedCookies);
```

Or am I doing it wrong?

**Comment by karashiiro** [comment]
Sorry for the late reply, I believe you need to use [`toJSON`](https://github.com/salesforce/tough-cookie#tojson-1) and [`Cookie.fromJSON`](https://github.com/salesforce/tough-cookie#cookiefromjsonstrorobj) to do this.

**Comment by louisgrasset** [comment]
I made an small util for this
https://github.com/louisgrasset/touitomamout/blob/main/src/helpers/cookies/get-cookies.ts

**Comment by JackSparrowf9** [comment]
If you store it to file, and you must rewrite your cookies to this format:

`
const loadedCookiesJSON = readFileSync('cookies.json', 'utf8');
const cookie = loadedCookiesJSON.map(c => {
// rewrite.....
})

// after rewrite cookie should be like this
const cookie = [
kdt=aaaa; domain=twitter.com; path=/; secure; httpOnly=false, 
twid="u=aaaa"; domain=twitter.com; path=/; secure; httpOnly=false,
ct0=aaaaa; domain=twitter.com; path=/; secure; httpOnly=false,
auth_token=aaaaa; domain=twitter.com; path=/; secure; httpOnly=false
]
const login = await scrape.setCookies(cookie)

// check login
const islogin = await scrape.isLoggedIn();
`

**Comment by karashiiro** [comment]
That's another way of doing it, `tough-cookie` accepts both `Cookie` instances (use `toJSON`/`fromJSON` for those) and raw cookie strings like what you have there.
