### ISSUE TITLE
Add a GitHub Action to test libraries

### ISSUE THREAD

**Issue by AleexMzz** [the-convocation/twitter-scraper#57]
I noticed a lot of errors when I ran the "npm run test" command.
![image](https://github.com/the-convocation/twitter-scraper/assets/24949093/eb44e111-65f3-4de6-8448-b240b77911b0)
Is this normal, did I do something wrong? If it's really errors, it would be nice to add a github action that automatically checks for errors in tests.

**Comment by karashiiro** [comment]
This is normal, and it is errors. The Twitter API changes at the speed of light.

There is a GHA that runs on a regular basis, and it's almost always failing.
