### ISSUE TITLE
Craft requests to different endpoints than the ones provided.

### ISSUE THREAD

**Issue by LiVIU245** [the-convocation/twitter-scraper#64]
Hi, I was wondering how could I make a request to different endpoints than the ones provided. For example Retweeters or Favoriters. Is there any way to do this without forking?

**Comment by karashiiro** [comment]
As in adding support for completely different endpoints? You would need to fork for that — if you just want to do a minor change to an existing endpoint request you can do that with a request interceptor, though (info in README).

**Comment by karashiiro** [comment]
It'll take some URL parsing work to do it with an interceptor, though, so even then it might be easier to fork.
